name: CI Workflow

on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Output personal information
        run: |
          echo "Сыромятников Аристарх Алексеевич"
          echo "M3111"
          echo "Ник на GitHub: Bleys999"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover

      - name: Check code style
        run: |
          pip install flake8
          flake8

      - name: Format code (if needed)
        run: |
          pip install black
          black .
