name: Workflow for Pull Requests and Pushes

on:
  push:
    branches:
      - master
      - release
      - develop
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  main-job:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Сыромятников Аристарх Алексеевич"
      GROUP: "М3111"

    steps:
      - name: Print info
        run: |
          echo "Full Name: $FULL_NAME"
          echo "Group: $GROUP"
          echo "GitHub Username: Bleys999"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s test -p "test_*.py"
