name: Python CI Workflow

on:
  push:
    branches:
      - main
      - release
      - develop
  pull_request:
    branches:
      - main
      - release
      - develop

env:
  FULL_NAME: "Сыромятников Аристарх Алексеевич"
  GROUP: "M3111"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print user information
        run: |
          echo "Full Name: ${{ env.FULL_NAME }}"
          echo "Group: ${{ env.GROUP }}"
          echo "GitHub Username: ${{ github.actor }}"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install pip and flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run tests
        run: python -m unittest discover -s ./test

      - name: Lint code with flake8
        run: flake8 .
